-- Wagner-GPT Memory + Settings schema (Phase 2).
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
-- Ports the mcp-memory-server design (all-MiniLM-L6-v2, 384-dim) to Supabase pgvector.

-- Vector support
create extension if not exists vector;

-- Semantic memories (mirrors the Weaviate "Memory" collection)
create table if not exists memories (
  id bigint generated by default as identity primary key,
  text text not null,
  summary text default '',
  embedding vector(384),
  category text default 'general',
  source text default 'chat',
  created_at bigint not null default 0,
  updated_at bigint not null default 0
);

-- Approximate-nearest-neighbour index for fast cosine search
create index if not exists memories_embedding_idx
  on memories using hnsw (embedding vector_cosine_ops);

-- Nearest memories by cosine distance. Recency reranking is applied client-side
-- (score = (1 - distance) - 0.01 * age_days), matching the original server.
create or replace function match_memories(query_embedding vector(384), match_count int default 15)
returns table (id bigint, text text, summary text, category text, source text, created_at bigint, distance float)
language sql stable as $$
  select m.id, m.text, m.summary, m.category, m.source, m.created_at,
         (m.embedding <=> query_embedding) as distance
  from memories m
  where m.embedding is not null
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

alter table memories enable row level security;
create policy "allow_all_memories" on memories for all using (true) with check (true);

-- Single-row settings: custom instructions + "about you" + memory toggle
create table if not exists user_settings (
  id int primary key default 1,
  about_you text default '',
  custom_instructions text default '',
  memory_enabled boolean default true,
  updated_at bigint default 0
);

alter table user_settings enable row level security;
create policy "allow_all_settings" on user_settings for all using (true) with check (true);
